services:
  db:
    image: postgres:15-alpine
    restart: always
    container_name: finance_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build: .
    restart: always
    container_name: finance_bot
    depends_on:
      - db
    # --- ЭТО КЛЮЧЕВОЙ МОМЕНТ ---
    network_mode: "host"
    # Бот будет использовать сеть сервера, минуя Docker DNS
    # ---------------------------
    env_file:
      - .env
    environment:
      # Теперь мы подключаемся к локальному IP сервера
      DATABASE_URL: postgresql+asyncpg://${DB_USER}:${DB_PASS}@127.0.0.1:5432/${DB_NAME}
    volumes:
      - ./config:/app/config

volumes:
  postgres_data:
